

// Books Object를 만들자..


//global variables
const context = {};

//test Data
let Data = {
    "BookName":"김치를 맛있게 만들어 먹기",
    "Index":"<div class=\"title\"><h1>나는 김치 마스터!</h1></div>",
    "Page":[
        {
            "BookName":"김치를 만드는 방법",
            "Index":"<div class=\"title\"><h1>같이 김치를 만들어 보자!</h1></div>",
            "Page":[
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 만드는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>배추를 산다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">고추를 산다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>둘을 퓨전시켜 만든다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"1"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무김치를 만드는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>열무 김치를 산다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">끝.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"2"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">고구마대 김치를 만드는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마를 산다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">고구마가 된다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>둘을 퓨전시키면 고구마대가 된다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"3"}
            ],
            "Date":"2019-10-12 15:56",
            "Type":"Book",
            "ID":"6"
        },
        {
            "BookName":"김치를 맛있게 먹는 방법",
            "Index":"<div class=\"title\"><h1>김치를 잘 만들었으면 잘 먹어보자!</h1></div>",
            "Page":[
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">배추김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>그냥 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\">밥과 같이 먹는다.</div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>고구마와 같이 먹는다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"4"},
                {"Title":"<div class=\"title\" contenteditable=\"true\">열무 김치를 맛있게 먹는 방법</div>","Contents":"<div id=\"main_text\">\n        <div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>굶은 다음에 먹는다. 시장이 반찬이다.</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>BBBBBBBBBBBB</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>CCCCCCCCCCCC</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>dddddddddddd</h1></div></div><div draggable=\"true\" class=\"writing_object\"><div class=\"text_object\" contenteditable=\"true\"><h1>eeeeeeeeeeee</h1></div></div></div>","date":"","Type":"Page", "ID":"5"},
            ],
            "Date":"2019-10-12 15:56",
            "Type":"Book",
            "ID":"7"
        }
    ],
    "Date":"2019-10-12 15:56",
    "Type":"Book",
    "ID":"123124151234123"
}

//Object
const Books = {
    Title:"", //해당 Book의 이름.
    Index:"", // index.html. 해당 Book의 index 페이지.
    Type:"", // Page인지 Book 인지 구분 해 주는 문자열.
    Date:"", // 해당 Book을 작성한 일자.
    Page:[], //순서 있는 배열. page에는 Books Object도 들어올 수 있음.
    ID:"" //ID값. SHA-1 알고리즘으로 생성
}

const Page ={
    Title:"",
    Contents:"",
    Date:"",
    Type:"Page",
    ID:"" //contents 내용을 sha-1로 계산함.
}

//Factory Function
/**
 * @constructor
 */
function myBook (){
    var myBookObject =Object.assign({}, Books)
    function addChapter(targetBook, data, number){
    }
    return myBookObject
}

//Utility Function
/**
 * @function
 * @param {Books}
 */
function loadBook(Books){
    //static values
    var contents = document.getElementsByClassName("viewer_board")[0]
    var sideNav = document.getElementsByClassName("viewer_side_nav")[0]
    // operation values
    var rootSideNavNode = makeSideNav(Books)
    rootSideNavNode.setAttribute("class","Books")
    rootSideNavNode.setAttribute("id",Books.ID)

    //sideNav 채우기
    sideNav.appendChild(rootSideNavNode)
    //index.html 넣기.
    contents.innerHTML = Books.Index
}

/**
 * @param {Event} event
 */
function changePage(event){
    var contents = document.getElementsByClassName("viewer_board")[0]
    event.stopPropagation()
    var contentData = findData(event.currentTarget.id, Data)
    if( contentData.Type =="Book"){
        console.log(contentData.Index)
        contents.innerHTML = contentData.Index
    }else{contents.innerHTML = contentData.Contents}
}

//Helper Function
function makeSideNav(Books){
    var sideElement;
    //Can make Side nav?
    if(Books.Type === "Book"){
        sideElement = document.createElement("div")
        sideElement.innerHTML = Books.BookName
        sideElement.setAttribute("id", Books.ID)
        Books.Page.forEach((index)=>{
            let inSideElement = makeSideNav(index)
            if(inSideElement){
                sideElement.appendChild(inSideElement)
            }
        })
    } else if(Books.Type === "Page"){
        sideElement = document.createElement("div")
        sideElement.innerHTML = Books.Title
        sideElement.setAttribute("id", Books.ID)
    } else {
        return false
    }
    sideElement.addEventListener("click", changePage)
    return sideElement
}

/**
* @param {String} id
* @param {Books | Page} jsonData
*/
function findData(id, jsonData){
    if(id == jsonData.ID){
        return jsonData
    } else {
        if(jsonData.Type == "Book"){
            for(let i =0; i < jsonData.Page.length; i++){
                let foundData = findData(id, jsonData.Page[i])
                if(foundData){
                    return foundData
                }
            }
        } else{
            return false
        }
    }
}
//test code
loadBook(Data)